version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  apibase:
    build: .
    command: ./node_modules/.bin/moleculer-runner services/api.service.js services/io.service.js services/room.service.js services/lab.service.js services/profile.service.js services/room.service.js services/users.service.js services/wallet.service.js
    env_file:
      - ./docker-compose.env
    environment:
      - NODE_ID=apibase
    ports:
      - "4001:4001"
      - "3001:3001"
      - "3210:3210"
    depends_on:
      - redis
      - mongodb
    deploy:
      replicas: 1

  partials:
    build: .
    command: ./node_modules/.bin/moleculer-runner services/_partial/currency.service.js services/_partial/ip_location.service.js
    env_file:
      - ./docker-compose.env
    environment:
      - NODE_ID=partials
    depends_on:
      - redis
      - mongodb
    deploy:
      replicas: 1

  admin:
    build: .
    command: ./node_modules/.bin/moleculer-runner services/admin/country.service.js
    env_file:
      - ./docker-compose.env
    environment:
      - NODE_ID=admin
    depends_on:
      - redis
      - mongodb
    deploy:
      replicas: 1

  screens:
    build: .
    command: ./node_modules/.bin/moleculer-runner services/screen/screen.service.js services/screen/device.service.js
    env_file:
      - ./docker-compose.env
    environment:
      - NODE_ID=screens
    depends_on:
      - redis
      - mongodb
    deploy:
      replicas: 1

  package:
    build: .
    command: ./node_modules/.bin/moleculer-runner services/package/packages.service.js
    env_file:
      - ./docker-compose.env
    environment:
      - NODE_ID=package
    depends_on:
      - redis
      - mongodb
    deploy:
      replicas: 1

  email:
    build: .
    command: ./node_modules/.bin/moleculer-runner services/email/email.service.js
    env_file:
      - ./docker-compose.env
    environment:
      - NODE_ID=email
    depends_on:
      - redis
      - mongodb
    deploy:
      replicas: 1

  source:
    build: .
    command: ./node_modules/.bin/moleculer-runner services/source/source.service.js services/source/layout.service.js services/source/channel.service.js services/source/playlist.service.js services/source/program.service.js
    env_file:
      - ./docker-compose.env
    environment:
      - NODE_ID=source
    depends_on:
      - redis
      - mongodb
    deploy:
      replicas: 1

  widget:
    build: .
    command: ./node_modules/.bin/moleculer-runner services/widget/widget.service.js services/widget/filemanager.service.js services/widget/module/image.service.js services/widget/module/video.service.js services/widget/module/instagram.service.js services/widget/module/worker/instagram.worker.js
    env_file:
      - ./docker-compose.env
    environment:
      - NODE_ID=widget
    depends_on:
      - redis
      - mongodb
    deploy:
      replicas: 1
